service: infra-cost-bot

provider:
  name: aws
  runtime: python3.6
  timeout: 30
  region: us-east-1
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ce:GetCostAndUsage"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource:
        - "arn:aws:ssm:us-east-1:398949996071:parameter/infra-cost/slack_token"
        - "arn:aws:ssm:us-east-1:398949996071:parameter/infra-cost/projects_list_url"

functions:
  infra-cost-bot:
    handler: infra-cost-bot.lambda_handler
    events:
      - http: POST infra-cost 
